spring.application.name=studybuddy


# Database H2 in memoria
spring.datasource.url=jdbc:h2:mem:studybuddy;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console per vedere i dati (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

#Groq AI configuration
ai.groq.api-key=${GROQ_API_KEY}
ai.groq.model=llama-3.3-70b-versatile